// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using QuanLyBenhVien.Data;

#nullable disable

namespace QuanLyBenhVien.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260731144342_LabDiagnosticsCore")]
    partial class LabDiagnosticsCore
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.9");

            modelBuilder.Entity("QuanLyBenhVien.Models.Appointment", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int?>("BacSiId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("BenhNhanId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("LyDoKham")
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("NgayTao")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<DateTime>("ThoiGian")
                        .HasColumnType("TEXT");

                    b.Property<string>("TrangThai")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("BacSiId");

                    b.HasIndex("BenhNhanId");

                    b.HasIndex("ThoiGian");

                    b.HasIndex("TrangThai");

                    b.ToTable("LichKham", t =>
                        {
                            t.HasCheckConstraint("CK_LichKham_TrangThai", "TrangThai IN ('ChoXacNhan','DaXacNhan','DangKham','HoanThanh','DaHuy','VangMat')");
                        });
                });

            modelBuilder.Entity("QuanLyBenhVien.Models.Article", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("AnhBia")
                        .HasMaxLength(300)
                        .HasColumnType("TEXT");

                    b.Property<string>("ChuyenMuc")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<bool>("DaXuatBan")
                        .HasColumnType("INTEGER");

                    b.Property<int>("LuotXem")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("NgayCapNhat")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("NgayDang")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<bool>("NoiBat")
                        .HasColumnType("INTEGER");

                    b.Property<string>("NoiDung")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("TacGia")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("TieuDe")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<string>("TomTat")
                        .IsRequired()
                        .HasMaxLength(400)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("TinTuc");
                });

            modelBuilder.Entity("QuanLyBenhVien.Models.AuditLog", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("ChiTiet")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("TEXT");

                    b.Property<int?>("DoiTuongId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("DoiTuongLoai")
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<string>("HanhDong")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("IpAddress")
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<int?>("NguoiDungId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("ThoiGian")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.HasKey("Id");

                    b.HasIndex("NguoiDungId");

                    b.ToTable("NhatKyHeThong");
                });

            modelBuilder.Entity("QuanLyBenhVien.Models.Department", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("MoTa")
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<string>("TenKhoa")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("ViTri")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Khoa");
                });

            modelBuilder.Entity("QuanLyBenhVien.Models.Dependent", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("BenhNhanId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("GioiTinh")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("TEXT");

                    b.Property<string>("HoTen")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<int>("NamSinh")
                        .HasColumnType("INTEGER");

                    b.Property<string>("NhomMau")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("TEXT");

                    b.Property<string>("QuanHe")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<string>("SoBHYT")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<string>("TienSuBenhLy")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("BenhNhanId");

                    b.ToTable("NguoiThan");
                });

            modelBuilder.Entity("QuanLyBenhVien.Models.Doctor", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("ChucVu")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<string>("ChuyenKhoa")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<bool>("DaXoa")
                        .HasColumnType("INTEGER");

                    b.Property<string>("HocVi")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<int>("KhoaId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("LichLamViec")
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("NgayXoa")
                        .HasColumnType("TEXT");

                    b.Property<int>("NguoiDungId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("SoNamKinhNghiem")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("XoaBoiId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("KhoaId");

                    b.HasIndex("NguoiDungId")
                        .IsUnique();

                    b.HasIndex("XoaBoiId");

                    b.ToTable("BacSi", t =>
                        {
                            t.HasCheckConstraint("CK_BacSi_ChucVu", "ChucVu IN ('Bác sĩ','Phó trưởng khoa','Trưởng khoa')");
                        });
                });

            modelBuilder.Entity("QuanLyBenhVien.Models.DoctorWorkSchedule", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("BacSiId")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("DangHoatDong")
                        .HasColumnType("INTEGER");

                    b.Property<TimeSpan>("GioBatDau")
                        .HasColumnType("TEXT");

                    b.Property<TimeSpan>("GioKetThuc")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("HieuLucDen")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("HieuLucTu")
                        .HasColumnType("TEXT");

                    b.Property<string>("PhongKham")
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<int>("SoBenhNhanToiDa")
                        .HasColumnType("INTEGER");

                    b.Property<int>("ThoiLuongKhamPhut")
                        .HasColumnType("INTEGER");

                    b.Property<int>("ThuTrongTuan")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("BacSiId", "ThuTrongTuan", "GioBatDau", "GioKetThuc")
                        .IsUnique();

                    b.ToTable("LichLamViecBacSi", t =>
                        {
                            t.HasCheckConstraint("CK_LichLamViecBacSi_GioKetThuc", "GioKetThuc > GioBatDau");

                            t.HasCheckConstraint("CK_LichLamViecBacSi_SoBenhNhanToiDa", "SoBenhNhanToiDa > 0");

                            t.HasCheckConstraint("CK_LichLamViecBacSi_ThoiLuongKhamPhut", "ThoiLuongKhamPhut BETWEEN 5 AND 240");
                        });
                });

            modelBuilder.Entity("QuanLyBenhVien.Models.DrugAllergyGroup", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<bool>("LaDuLieuMinhHoa")
                        .HasColumnType("INTEGER");

                    b.Property<string>("MoTa")
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<string>("TenNhom")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("NhomHoatChatCheoPhanUng");
                });

            modelBuilder.Entity("QuanLyBenhVien.Models.DrugAllergyGroupMember", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("HoatChat")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("TEXT");

                    b.Property<int>("NhomId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("HoatChat");

                    b.HasIndex("NhomId");

                    b.ToTable("ThanhVienNhomHoatChat");
                });

            modelBuilder.Entity("QuanLyBenhVien.Models.DrugInteraction", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("HoatChatA")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("TEXT");

                    b.Property<string>("HoatChatB")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("TEXT");

                    b.Property<bool>("LaDuLieuMinhHoa")
                        .HasColumnType("INTEGER");

                    b.Property<string>("MoTa")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<string>("MucDoTuongTac")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("NgayTao")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<string>("NguonNhap")
                        .HasMaxLength(30)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("HoatChatA", "HoatChatB");

                    b.ToTable("TuongTacThuoc", t =>
                        {
                            t.HasCheckConstraint("CK_TuongTacThuoc_MucDo", "MucDoTuongTac IN ('ChongChiDinh','NghiemTrong','TrungBinh','Nhe')");
                        });
                });

            modelBuilder.Entity("QuanLyBenhVien.Models.ExaminationRecord", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<decimal?>("BMI")
                        .HasColumnType("decimal(4, 2)");

                    b.Property<decimal?>("CanNang")
                        .HasColumnType("decimal(5, 2)");

                    b.Property<string>("ChanDoan")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<string>("ChiDinhCLS")
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<decimal?>("ChieuCao")
                        .HasColumnType("decimal(5, 2)");

                    b.Property<string>("GhiChuCLSCuaBacSi")
                        .HasMaxLength(1000)
                        .HasColumnType("TEXT");

                    b.Property<string>("HuyetAp")
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.Property<string>("KetQuaCLS")
                        .HasMaxLength(1000)
                        .HasColumnType("TEXT");

                    b.Property<int>("LichKhamId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("LoiDan")
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("NgayHenTaiKham")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("NgayKham")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<decimal?>("NhietDo")
                        .HasColumnType("decimal(4, 1)");

                    b.Property<int?>("NhipTim")
                        .HasColumnType("INTEGER");

                    b.Property<string>("TrieuChung")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("LichKhamId")
                        .IsUnique();

                    b.ToTable("PhieuKham");
                });

            modelBuilder.Entity("QuanLyBenhVien.Models.FamilyHistory", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("BenhNhanId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("GhiChu")
                        .HasMaxLength(300)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("NgayGhiNhan")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<string>("QuanHe")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<string>("TenBenh")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("BenhNhanId");

                    b.ToTable("TienSuGiaDinh");
                });

            modelBuilder.Entity("QuanLyBenhVien.Models.GoodsReceipt", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("GhiChu")
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<string>("KhoNhap")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.Property<string>("LoaiNhap")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.Property<string>("LyDoTuChoi")
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<string>("MaPhieu")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("NgayCapNhat")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("NgayDuyet")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("NgayHoaDon")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("NgayNhap")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<DateTime>("NgayTao")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<int?>("NguoiDuyetId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("NguoiGiaoHang")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<int>("NguoiTaoId")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("NhaCungCapId")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("PhieuGocId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("SoHoaDonNCC")
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<decimal>("TienVAT")
                        .HasColumnType("decimal(18, 2)");

                    b.Property<int>("TongSoMatHang")
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("TongThanhToan")
                        .HasColumnType("decimal(18, 2)");

                    b.Property<decimal>("TongTienTruocVAT")
                        .HasColumnType("decimal(18, 2)");

                    b.Property<string>("TrangThai")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("MaPhieu")
                        .IsUnique();

                    b.HasIndex("NguoiDuyetId");

                    b.HasIndex("NguoiTaoId");

                    b.HasIndex("NhaCungCapId");

                    b.HasIndex("PhieuGocId");

                    b.HasIndex("TrangThai");

                    b.ToTable("PhieuNhapKho", t =>
                        {
                            t.HasCheckConstraint("CK_PhieuNhapKho_KhoNhap", "KhoNhap IN ('KhoChan','KhoLe','NhaThuoc')");

                            t.HasCheckConstraint("CK_PhieuNhapKho_LoaiNhap", "LoaiNhap IN ('MuaNCC','ChuyenKho','HangTraVe','VienTro')");

                            t.HasCheckConstraint("CK_PhieuNhapKho_TienVAT", "TienVAT >= 0");

                            t.HasCheckConstraint("CK_PhieuNhapKho_TongSoMatHang", "TongSoMatHang >= 0");

                            t.HasCheckConstraint("CK_PhieuNhapKho_TongThanhToan", "TongThanhToan >= 0");

                            t.HasCheckConstraint("CK_PhieuNhapKho_TongTienTruocVAT", "TongTienTruocVAT >= 0");

                            t.HasCheckConstraint("CK_PhieuNhapKho_TrangThai", "TrangThai IN ('Nhap','ChoDuyet','DaDuyet','TuChoi','DaHuy')");
                        });
                });

            modelBuilder.Entity("QuanLyBenhVien.Models.GoodsReceiptDetail", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<bool>("CongDonVaoLoHienCo")
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("DonGia")
                        .HasColumnType("decimal(18, 2)");

                    b.Property<DateTime>("HanSuDung")
                        .HasColumnType("TEXT");

                    b.Property<int?>("LoThuocId")
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("PhanTramVAT")
                        .HasColumnType("decimal(5, 2)");

                    b.Property<int>("PhieuNhapKhoId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("SoLo")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<int>("SoLuong")
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("ThanhTien")
                        .HasColumnType("decimal(18, 2)");

                    b.Property<int>("ThuocId")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("XacNhanCanDate")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("LoThuocId");

                    b.HasIndex("PhieuNhapKhoId");

                    b.HasIndex("ThuocId");

                    b.ToTable("PhieuNhapKhoChiTiet", t =>
                        {
                            t.HasCheckConstraint("CK_PhieuNhapKhoChiTiet_DonGia", "DonGia >= 0");

                            t.HasCheckConstraint("CK_PhieuNhapKhoChiTiet_PhanTramVAT", "PhanTramVAT BETWEEN 0 AND 100");

                            t.HasCheckConstraint("CK_PhieuNhapKhoChiTiet_SoLuong", "SoLuong > 0");

                            t.HasCheckConstraint("CK_PhieuNhapKhoChiTiet_ThanhTien", "ThanhTien >= 0");
                        });
                });

            modelBuilder.Entity("QuanLyBenhVien.Models.Immunization", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("BenhNhanId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("GhiChu")
                        .HasMaxLength(300)
                        .HasColumnType("TEXT");

                    b.Property<string>("MuiSo")
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("NgayTiem")
                        .HasColumnType("TEXT");

                    b.Property<string>("TenVaccine")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("BenhNhanId");

                    b.ToTable("TiemChung");
                });

            modelBuilder.Entity("QuanLyBenhVien.Models.Invoice", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("MaGiaoDich")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("NgayTao")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<DateTime?>("NgayThanhToan")
                        .HasColumnType("TEXT");

                    b.Property<int>("PhieuKhamId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("PhuongThuc")
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<decimal>("TongTien")
                        .HasColumnType("decimal(18, 2)");

                    b.Property<string>("TrangThaiThanhToan")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("PhieuKhamId")
                        .IsUnique();

                    b.ToTable("HoaDon", t =>
                        {
                            t.HasCheckConstraint("CK_HoaDon_PhuongThuc", "PhuongThuc IS NULL OR PhuongThuc IN ('TienMat','ChuyenKhoan','Online (MoMo)','Online (VNPay)','Online (ZaloPay)','Online')");

                            t.HasCheckConstraint("CK_HoaDon_TongTien", "TongTien >= 0");

                            t.HasCheckConstraint("CK_HoaDon_TrangThaiThanhToan", "TrangThaiThanhToan IN ('ChuaThanhToan','DaThanhToan','DangXuLy','QuaHan','ThanhToanThatBai','DaHuy')");
                        });
                });

            modelBuilder.Entity("QuanLyBenhVien.Models.InvoiceDetail", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("HoaDonId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("LoaiPhi")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<decimal>("SoTien")
                        .HasColumnType("decimal(18, 2)");

                    b.HasKey("Id");

                    b.HasIndex("HoaDonId");

                    b.ToTable("ChiTietHoaDon", t =>
                        {
                            t.HasCheckConstraint("CK_ChiTietHoaDon_SoTien", "SoTien >= 0");
                        });
                });

            modelBuilder.Entity("QuanLyBenhVien.Models.LabOrder", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("BacSiChiDinhId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("BenhNhanId")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("BoChiDinhCLSId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("GhiChuChiDinh")
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<string>("MaPhieu")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("NgayChiDinh")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<int>("PhieuKhamId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("BacSiChiDinhId");

                    b.HasIndex("BenhNhanId");

                    b.HasIndex("BoChiDinhCLSId");

                    b.HasIndex("MaPhieu")
                        .IsUnique();

                    b.HasIndex("PhieuKhamId");

                    b.ToTable("PhieuChiDinhCLS");
                });

            modelBuilder.Entity("QuanLyBenhVien.Models.LabOrderBundle", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<bool>("DangHoatDong")
                        .HasColumnType("INTEGER");

                    b.Property<string>("MoTa")
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<string>("TenBo")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("BoChiDinhCLS");
                });

            modelBuilder.Entity("QuanLyBenhVien.Models.LabOrderBundleItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("BoChiDinhCLSId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("DichVuCLSId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("DichVuCLSId");

                    b.HasIndex("BoChiDinhCLSId", "DichVuCLSId")
                        .IsUnique();

                    b.ToTable("ChiTietBoChiDinhCLS");
                });

            modelBuilder.Entity("QuanLyBenhVien.Models.LabOrderItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("DichVuCLSId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("LyDoHuy")
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("NgayNhanThucHien")
                        .HasColumnType("TEXT");

                    b.Property<int?>("NguoiNhanId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("PhieuChiDinhCLSId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("TrangThai")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("DichVuCLSId");

                    b.HasIndex("NguoiNhanId");

                    b.HasIndex("PhieuChiDinhCLSId");

                    b.ToTable("ChiTietPhieuChiDinhCLS", t =>
                        {
                            t.HasCheckConstraint("CK_ChiTietPhieuChiDinhCLS_TrangThai", "TrangThai IN ('ChoThucHien','DangThucHien','DaCoKetQua','DaHuy')");
                        });
                });

            modelBuilder.Entity("QuanLyBenhVien.Models.LabResult", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("ChiTietPhieuChiDinhCLSId")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("CoBatThuong")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("DaXem")
                        .HasColumnType("INTEGER");

                    b.Property<string>("KetLuan")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("NgayTra")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<DateTime?>("NgayXem")
                        .HasColumnType("TEXT");

                    b.Property<string>("NguoiDuyetTen")
                        .HasMaxLength(150)
                        .HasColumnType("TEXT");

                    b.Property<int>("NguoiThucHienId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("ChiTietPhieuChiDinhCLSId")
                        .IsUnique();

                    b.HasIndex("NguoiThucHienId");

                    b.ToTable("KetQuaCLS");
                });

            modelBuilder.Entity("QuanLyBenhVien.Models.LabResultFile", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("ContentType")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<int>("KetQuaCLSId")
                        .HasColumnType("INTEGER");

                    b.Property<long>("KichThuoc")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("NgayTaiLen")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<string>("TenGoc")
                        .IsRequired()
                        .HasMaxLength(260)
                        .HasColumnType("TEXT");

                    b.Property<string>("TenLuuTru")
                        .IsRequired()
                        .HasMaxLength(260)
                        .HasColumnType("TEXT");

                    b.Property<int>("ThuTu")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("KetQuaCLSId");

                    b.ToTable("FileKetQuaCLS");
                });

            modelBuilder.Entity("QuanLyBenhVien.Models.LabServiceCatalog", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<bool>("DangHoatDong")
                        .HasColumnType("INTEGER");

                    b.Property<string>("GhiChu")
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<decimal>("Gia")
                        .HasColumnType("decimal(12, 2)");

                    b.Property<string>("MaDichVu")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("TEXT");

                    b.Property<string>("NhomCLS")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("TEXT");

                    b.Property<string>("NoiThucHien")
                        .HasMaxLength(150)
                        .HasColumnType("TEXT");

                    b.Property<string>("TenDichVu")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("MaDichVu")
                        .IsUnique();

                    b.ToTable("DichVuCLS", t =>
                        {
                            t.HasCheckConstraint("CK_DichVuCLS_Gia", "Gia >= 0");

                            t.HasCheckConstraint("CK_DichVuCLS_NhomCLS", "NhomCLS IN ('HuyetHoc','SinhHoa','ViSinh','CDHA','ThamDoChucNang','GiaiPhauBenh')");
                        });
                });

            modelBuilder.Entity("QuanLyBenhVien.Models.Medicine", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<bool>("CoBaoHiemYTe")
                        .HasColumnType("INTEGER");

                    b.Property<string>("DonViTinh")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<decimal>("Gia")
                        .HasColumnType("decimal(18, 2)");

                    b.Property<string>("HamLuong")
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<string>("HoatChat")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("TEXT");

                    b.Property<int?>("LieuToiDaMoiNgay")
                        .HasColumnType("INTEGER");

                    b.Property<decimal?>("LieuToiDaMoiNgayTheoKg")
                        .HasColumnType("decimal(10, 4)");

                    b.Property<int>("NguongToiThieu")
                        .HasColumnType("INTEGER");

                    b.Property<string>("QuyCachDongGoi")
                        .HasMaxLength(150)
                        .HasColumnType("TEXT");

                    b.Property<int?>("QuyCachSoLuong")
                        .HasColumnType("INTEGER");

                    b.Property<string>("TenThuoc")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("TEXT");

                    b.Property<int>("TonKho")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("Thuoc", t =>
                        {
                            t.HasCheckConstraint("CK_Thuoc_Gia", "Gia >= 0");

                            t.HasCheckConstraint("CK_Thuoc_NguongToiThieu", "NguongToiThieu >= 0");

                            t.HasCheckConstraint("CK_Thuoc_TonKho", "TonKho >= 0");
                        });
                });

            modelBuilder.Entity("QuanLyBenhVien.Models.MedicineBatch", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<decimal?>("GiaNhap")
                        .HasColumnType("decimal(18, 2)");

                    b.Property<DateTime>("HanSuDung")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("NgayNhap")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasDefaultValueSql("'2000-01-01 00:00:00'");

                    b.Property<int?>("NhaCungCapId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("SoLo")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<int>("SoLuongNhap")
                        .HasColumnType("INTEGER");

                    b.Property<int>("SoLuongTon")
                        .HasColumnType("INTEGER");

                    b.Property<int>("ThuocId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("NhaCungCapId");

                    b.HasIndex("ThuocId");

                    b.ToTable("LoThuoc", t =>
                        {
                            t.HasCheckConstraint("CK_LoThuoc_GiaNhap", "GiaNhap IS NULL OR GiaNhap >= 0");

                            t.HasCheckConstraint("CK_LoThuoc_HanSuDung", "HanSuDung >= NgayNhap");

                            t.HasCheckConstraint("CK_LoThuoc_SoLuongNhap", "SoLuongNhap > 0");

                            t.HasCheckConstraint("CK_LoThuoc_SoLuongTon", "SoLuongTon >= 0");

                            t.HasCheckConstraint("CK_LoThuoc_TonKhongVuotQuaNhap", "SoLuongTon <= SoLuongNhap");
                        });
                });

            modelBuilder.Entity("QuanLyBenhVien.Models.Notification", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<bool>("DaDoc")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("NgayGui")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<int>("NguoiDungId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("NoiDung")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("NguoiDungId");

                    b.ToTable("ThongBao");
                });

            modelBuilder.Entity("QuanLyBenhVien.Models.PasswordResetRequest", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("IpAddress")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<string>("Kenh")
                        .HasMaxLength(10)
                        .HasColumnType("TEXT");

                    b.Property<string>("KhoiTaoBoi")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("LanGuiGanNhatLuc")
                        .HasColumnType("TEXT");

                    b.Property<bool>("MaDaDung")
                        .HasColumnType("INTEGER");

                    b.Property<string>("MaXacNhanHash")
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("NgayTao")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<int?>("NguoiDungId")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("ResetTokenDaDung")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ResetTokenHash")
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<int>("SoLanGuiLai")
                        .HasColumnType("INTEGER");

                    b.Property<int>("SoLanNhapSai")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("ThoiHanMa")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("ThoiHanResetToken")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ResetTokenHash");

                    b.HasIndex("IpAddress", "NgayTao");

                    b.HasIndex("NguoiDungId", "NgayTao");

                    b.ToTable("YeuCauKhoiPhucMatKhau", t =>
                        {
                            t.HasCheckConstraint("CK_YeuCauKhoiPhucMatKhau_Kenh", "Kenh IS NULL OR Kenh IN ('Email','Sdt')");

                            t.HasCheckConstraint("CK_YeuCauKhoiPhucMatKhau_KhoiTaoBoi", "KhoiTaoBoi IN ('TuPhucVu','Admin')");
                        });
                });

            modelBuilder.Entity("QuanLyBenhVien.Models.Patient", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<bool>("DaXoa")
                        .HasColumnType("INTEGER");

                    b.Property<string>("DiUng")
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<string>("GioiTinh")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("TEXT");

                    b.Property<string>("MucDoDiUng")
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("NgayHetHanBHYT")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("NgaySinh")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("NgayXoa")
                        .HasColumnType("TEXT");

                    b.Property<int>("NguoiDungId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("NhomMau")
                        .HasMaxLength(10)
                        .HasColumnType("TEXT");

                    b.Property<string>("SoBHYT")
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<string>("SoCCCD")
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.Property<string>("TienSuBenh")
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<int?>("XoaBoiId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("NguoiDungId")
                        .IsUnique();

                    b.HasIndex("SoBHYT")
                        .IsUnique();

                    b.HasIndex("SoCCCD")
                        .IsUnique();

                    b.HasIndex("XoaBoiId");

                    b.ToTable("BenhNhan", t =>
                        {
                            t.HasCheckConstraint("CK_BenhNhan_MucDoDiUng", "MucDoDiUng IS NULL OR MucDoDiUng IN ('Nhe','TrungBinh','NghiemTrong')");

                            t.HasCheckConstraint("CK_BenhNhan_NgaySinh", "NgaySinh <= CURRENT_TIMESTAMP");
                        });
                });

            modelBuilder.Entity("QuanLyBenhVien.Models.PatientDocument", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("BenhNhanId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ContentType")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("GhiChu")
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<long>("KichThuoc")
                        .HasColumnType("INTEGER");

                    b.Property<string>("LoaiTaiLieu")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("NgayTaiLen")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<string>("TenLuuTru")
                        .IsRequired()
                        .HasMaxLength(260)
                        .HasColumnType("TEXT");

                    b.Property<string>("TenTaiLieu")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("BenhNhanId");

                    b.ToTable("TaiLieuBenhNhan");
                });

            modelBuilder.Entity("QuanLyBenhVien.Models.PatientHealthMetric", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("BenhNhanId")
                        .HasColumnType("INTEGER");

                    b.Property<decimal?>("CanNang")
                        .HasColumnType("decimal(5, 2)");

                    b.Property<decimal?>("ChieuCao")
                        .HasColumnType("decimal(5, 2)");

                    b.Property<decimal?>("DuongHuyet")
                        .HasColumnType("decimal(5, 2)");

                    b.Property<string>("GhiChu")
                        .HasMaxLength(300)
                        .HasColumnType("TEXT");

                    b.Property<int?>("HuyetApTamThu")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("HuyetApTamTruong")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("NgayDo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<DateTime>("NgayTao")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<int?>("NhipTim")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("BenhNhanId");

                    b.ToTable("ChiSoSucKhoeTuDo");
                });

            modelBuilder.Entity("QuanLyBenhVien.Models.Prescription", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("BacSiKeId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("LyDoHuy")
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("NgayKe")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<int>("PhieuKhamId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("TrangThai")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT")
                        .HasDefaultValue("ChoCapPhat");

                    b.HasKey("Id");

                    b.HasIndex("BacSiKeId");

                    b.HasIndex("PhieuKhamId")
                        .IsUnique();

                    b.ToTable("DonThuoc", t =>
                        {
                            t.HasCheckConstraint("CK_DonThuoc_TrangThai", "TrangThai IN ('Nhap','ChoCapPhat','DaCapPhat','DuocPhanHoi','DaHuy')");
                        });
                });

            modelBuilder.Entity("QuanLyBenhVien.Models.PrescriptionBatchAllocation", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("ChiTietDonThuocId")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("DaHoanTra")
                        .HasColumnType("INTEGER");

                    b.Property<int>("LoThuocId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("NgayPhanBo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<int>("SoLuongLay")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("ChiTietDonThuocId");

                    b.HasIndex("LoThuocId");

                    b.ToTable("PhanBoLoThuocDonThuoc");
                });

            modelBuilder.Entity("QuanLyBenhVien.Models.PrescriptionDetail", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("DonThuocId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("DuongDung")
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<string>("HuongDanSuDung")
                        .HasMaxLength(300)
                        .HasColumnType("TEXT");

                    b.Property<string>("LieuDung")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<decimal?>("LieuMoiLan")
                        .HasColumnType("decimal(10, 2)");

                    b.Property<int?>("SoLanMoiNgay")
                        .HasColumnType("INTEGER");

                    b.Property<int>("SoLuong")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("SoNgayDung")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ThoiDiemDung")
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<int>("ThuocId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("DonThuocId");

                    b.HasIndex("ThuocId");

                    b.ToTable("ChiTietDonThuoc", t =>
                        {
                            t.HasCheckConstraint("CK_ChiTietDonThuoc_SoLuong", "SoLuong > 0");
                        });
                });

            modelBuilder.Entity("QuanLyBenhVien.Models.Review", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("BacSiId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("BenhNhanId")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("LichKhamId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("NgayTao")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<string>("NhanXet")
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<int>("SoSao")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("BacSiId");

                    b.HasIndex("BenhNhanId");

                    b.HasIndex("LichKhamId")
                        .IsUnique();

                    b.ToTable("DanhGia", t =>
                        {
                            t.HasCheckConstraint("CK_DanhGia_SoSao", "SoSao BETWEEN 1 AND 5");
                        });
                });

            modelBuilder.Entity("QuanLyBenhVien.Models.RolePermission", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int?>("CapNhatBoiId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CapNhatLuc")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<bool>("DuocPhep")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ModuleKey")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("VaiTro")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("CapNhatBoiId");

                    b.HasIndex("VaiTro", "ModuleKey")
                        .IsUnique();

                    b.ToTable("PhanQuyenVaiTro");
                });

            modelBuilder.Entity("QuanLyBenhVien.Models.Service", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("Gia")
                        .HasColumnType("decimal(18, 2)");

                    b.Property<int>("KhoaId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("TenDichVu")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("KhoaId");

                    b.ToTable("DichVu", t =>
                        {
                            t.HasCheckConstraint("CK_DichVu_Gia", "Gia >= 0");
                        });
                });

            modelBuilder.Entity("QuanLyBenhVien.Models.Supplier", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<bool>("DangHoatDong")
                        .HasColumnType("INTEGER");

                    b.Property<string>("DiaChi")
                        .HasMaxLength(300)
                        .HasColumnType("TEXT");

                    b.Property<string>("Email")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("MaSoThue")
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("NgayTao")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<string>("NguoiLienHe")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("SoDienThoai")
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.Property<string>("TenNhaCungCap")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("TenNhaCungCap");

                    b.ToTable("NhaCungCap");
                });

            modelBuilder.Entity("QuanLyBenhVien.Models.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("AnhDaiDien")
                        .HasMaxLength(260)
                        .HasColumnType("TEXT");

                    b.Property<bool>("DaXoa")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("DuocDuyetPhieuNhapKho")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("DuocXuLyCLS")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("HoTen")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("MatKhauHash")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("MatKhauTamHetHan")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("NgayTao")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<DateTime?>("NgayXoa")
                        .HasColumnType("TEXT");

                    b.Property<bool>("PhaiDoiMatKhau")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Sdt")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.Property<string>("SecurityStamp")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<string>("TrangThai")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<string>("VaiTro")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<int?>("XoaBoiId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.HasIndex("Sdt")
                        .IsUnique();

                    b.HasIndex("XoaBoiId");

                    b.ToTable("NguoiDung", t =>
                        {
                            t.HasCheckConstraint("CK_NguoiDung_TrangThai", "TrangThai IN ('Active','Blocked')");

                            t.HasCheckConstraint("CK_NguoiDung_VaiTro", "VaiTro IN ('Admin','Doctor','Patient')");
                        });
                });

            modelBuilder.Entity("QuanLyBenhVien.Models.Appointment", b =>
                {
                    b.HasOne("QuanLyBenhVien.Models.Doctor", "Doctor")
                        .WithMany()
                        .HasForeignKey("BacSiId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("QuanLyBenhVien.Models.Patient", "Patient")
                        .WithMany()
                        .HasForeignKey("BenhNhanId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Doctor");

                    b.Navigation("Patient");
                });

            modelBuilder.Entity("QuanLyBenhVien.Models.AuditLog", b =>
                {
                    b.HasOne("QuanLyBenhVien.Models.User", "User")
                        .WithMany()
                        .HasForeignKey("NguoiDungId");

                    b.Navigation("User");
                });

            modelBuilder.Entity("QuanLyBenhVien.Models.Dependent", b =>
                {
                    b.HasOne("QuanLyBenhVien.Models.Patient", "Patient")
                        .WithMany("Dependents")
                        .HasForeignKey("BenhNhanId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Patient");
                });

            modelBuilder.Entity("QuanLyBenhVien.Models.Doctor", b =>
                {
                    b.HasOne("QuanLyBenhVien.Models.Department", "Department")
                        .WithMany()
                        .HasForeignKey("KhoaId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("QuanLyBenhVien.Models.User", "User")
                        .WithOne("DoctorProfile")
                        .HasForeignKey("QuanLyBenhVien.Models.Doctor", "NguoiDungId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("QuanLyBenhVien.Models.User", "XoaBoi")
                        .WithMany()
                        .HasForeignKey("XoaBoiId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Department");

                    b.Navigation("User");

                    b.Navigation("XoaBoi");
                });

            modelBuilder.Entity("QuanLyBenhVien.Models.DoctorWorkSchedule", b =>
                {
                    b.HasOne("QuanLyBenhVien.Models.Doctor", "Doctor")
                        .WithMany("WorkSchedules")
                        .HasForeignKey("BacSiId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Doctor");
                });

            modelBuilder.Entity("QuanLyBenhVien.Models.DrugAllergyGroupMember", b =>
                {
                    b.HasOne("QuanLyBenhVien.Models.DrugAllergyGroup", "Nhom")
                        .WithMany("ThanhVien")
                        .HasForeignKey("NhomId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Nhom");
                });

            modelBuilder.Entity("QuanLyBenhVien.Models.ExaminationRecord", b =>
                {
                    b.HasOne("QuanLyBenhVien.Models.Appointment", "Appointment")
                        .WithOne()
                        .HasForeignKey("QuanLyBenhVien.Models.ExaminationRecord", "LichKhamId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Appointment");
                });

            modelBuilder.Entity("QuanLyBenhVien.Models.FamilyHistory", b =>
                {
                    b.HasOne("QuanLyBenhVien.Models.Patient", "Patient")
                        .WithMany()
                        .HasForeignKey("BenhNhanId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Patient");
                });

            modelBuilder.Entity("QuanLyBenhVien.Models.GoodsReceipt", b =>
                {
                    b.HasOne("QuanLyBenhVien.Models.User", "NguoiDuyet")
                        .WithMany()
                        .HasForeignKey("NguoiDuyetId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("QuanLyBenhVien.Models.User", "NguoiTao")
                        .WithMany()
                        .HasForeignKey("NguoiTaoId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("QuanLyBenhVien.Models.Supplier", "NhaCungCap")
                        .WithMany("PhieuNhaps")
                        .HasForeignKey("NhaCungCapId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("QuanLyBenhVien.Models.GoodsReceipt", "PhieuGoc")
                        .WithMany()
                        .HasForeignKey("PhieuGocId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.Navigation("NguoiDuyet");

                    b.Navigation("NguoiTao");

                    b.Navigation("NhaCungCap");

                    b.Navigation("PhieuGoc");
                });

            modelBuilder.Entity("QuanLyBenhVien.Models.GoodsReceiptDetail", b =>
                {
                    b.HasOne("QuanLyBenhVien.Models.MedicineBatch", "LoThuoc")
                        .WithMany()
                        .HasForeignKey("LoThuocId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("QuanLyBenhVien.Models.GoodsReceipt", "PhieuNhapKho")
                        .WithMany("ChiTiet")
                        .HasForeignKey("PhieuNhapKhoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("QuanLyBenhVien.Models.Medicine", "Medicine")
                        .WithMany()
                        .HasForeignKey("ThuocId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("LoThuoc");

                    b.Navigation("Medicine");

                    b.Navigation("PhieuNhapKho");
                });

            modelBuilder.Entity("QuanLyBenhVien.Models.Immunization", b =>
                {
                    b.HasOne("QuanLyBenhVien.Models.Patient", "Patient")
                        .WithMany()
                        .HasForeignKey("BenhNhanId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Patient");
                });

            modelBuilder.Entity("QuanLyBenhVien.Models.Invoice", b =>
                {
                    b.HasOne("QuanLyBenhVien.Models.ExaminationRecord", "ExaminationRecord")
                        .WithOne()
                        .HasForeignKey("QuanLyBenhVien.Models.Invoice", "PhieuKhamId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("ExaminationRecord");
                });

            modelBuilder.Entity("QuanLyBenhVien.Models.InvoiceDetail", b =>
                {
                    b.HasOne("QuanLyBenhVien.Models.Invoice", "Invoice")
                        .WithMany("InvoiceDetails")
                        .HasForeignKey("HoaDonId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Invoice");
                });

            modelBuilder.Entity("QuanLyBenhVien.Models.LabOrder", b =>
                {
                    b.HasOne("QuanLyBenhVien.Models.Doctor", "BacSiChiDinh")
                        .WithMany()
                        .HasForeignKey("BacSiChiDinhId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("QuanLyBenhVien.Models.Patient", "Patient")
                        .WithMany()
                        .HasForeignKey("BenhNhanId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("QuanLyBenhVien.Models.LabOrderBundle", "BoChiDinh")
                        .WithMany()
                        .HasForeignKey("BoChiDinhCLSId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("QuanLyBenhVien.Models.ExaminationRecord", "ExaminationRecord")
                        .WithMany()
                        .HasForeignKey("PhieuKhamId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("BacSiChiDinh");

                    b.Navigation("BoChiDinh");

                    b.Navigation("ExaminationRecord");

                    b.Navigation("Patient");
                });

            modelBuilder.Entity("QuanLyBenhVien.Models.LabOrderBundleItem", b =>
                {
                    b.HasOne("QuanLyBenhVien.Models.LabOrderBundle", "BoChiDinh")
                        .WithMany("ThanhVien")
                        .HasForeignKey("BoChiDinhCLSId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("QuanLyBenhVien.Models.LabServiceCatalog", "DichVu")
                        .WithMany("ThuocCacBo")
                        .HasForeignKey("DichVuCLSId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("BoChiDinh");

                    b.Navigation("DichVu");
                });

            modelBuilder.Entity("QuanLyBenhVien.Models.LabOrderItem", b =>
                {
                    b.HasOne("QuanLyBenhVien.Models.LabServiceCatalog", "DichVu")
                        .WithMany()
                        .HasForeignKey("DichVuCLSId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("QuanLyBenhVien.Models.User", "NguoiNhan")
                        .WithMany()
                        .HasForeignKey("NguoiNhanId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("QuanLyBenhVien.Models.LabOrder", "PhieuChiDinh")
                        .WithMany("ChiTiet")
                        .HasForeignKey("PhieuChiDinhCLSId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("DichVu");

                    b.Navigation("NguoiNhan");

                    b.Navigation("PhieuChiDinh");
                });

            modelBuilder.Entity("QuanLyBenhVien.Models.LabResult", b =>
                {
                    b.HasOne("QuanLyBenhVien.Models.LabOrderItem", "ChiTietPhieuChiDinh")
                        .WithOne("KetQua")
                        .HasForeignKey("QuanLyBenhVien.Models.LabResult", "ChiTietPhieuChiDinhCLSId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("QuanLyBenhVien.Models.User", "NguoiThucHien")
                        .WithMany()
                        .HasForeignKey("NguoiThucHienId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("ChiTietPhieuChiDinh");

                    b.Navigation("NguoiThucHien");
                });

            modelBuilder.Entity("QuanLyBenhVien.Models.LabResultFile", b =>
                {
                    b.HasOne("QuanLyBenhVien.Models.LabResult", "KetQua")
                        .WithMany("Files")
                        .HasForeignKey("KetQuaCLSId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("KetQua");
                });

            modelBuilder.Entity("QuanLyBenhVien.Models.MedicineBatch", b =>
                {
                    b.HasOne("QuanLyBenhVien.Models.Supplier", "NhaCungCap")
                        .WithMany()
                        .HasForeignKey("NhaCungCapId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("QuanLyBenhVien.Models.Medicine", "Medicine")
                        .WithMany("LoThuocs")
                        .HasForeignKey("ThuocId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Medicine");

                    b.Navigation("NhaCungCap");
                });

            modelBuilder.Entity("QuanLyBenhVien.Models.Notification", b =>
                {
                    b.HasOne("QuanLyBenhVien.Models.User", "User")
                        .WithMany()
                        .HasForeignKey("NguoiDungId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("QuanLyBenhVien.Models.PasswordResetRequest", b =>
                {
                    b.HasOne("QuanLyBenhVien.Models.User", "User")
                        .WithMany()
                        .HasForeignKey("NguoiDungId");

                    b.Navigation("User");
                });

            modelBuilder.Entity("QuanLyBenhVien.Models.Patient", b =>
                {
                    b.HasOne("QuanLyBenhVien.Models.User", "User")
                        .WithOne("PatientProfile")
                        .HasForeignKey("QuanLyBenhVien.Models.Patient", "NguoiDungId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("QuanLyBenhVien.Models.User", "XoaBoi")
                        .WithMany()
                        .HasForeignKey("XoaBoiId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("User");

                    b.Navigation("XoaBoi");
                });

            modelBuilder.Entity("QuanLyBenhVien.Models.PatientDocument", b =>
                {
                    b.HasOne("QuanLyBenhVien.Models.Patient", "Patient")
                        .WithMany()
                        .HasForeignKey("BenhNhanId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Patient");
                });

            modelBuilder.Entity("QuanLyBenhVien.Models.PatientHealthMetric", b =>
                {
                    b.HasOne("QuanLyBenhVien.Models.Patient", "Patient")
                        .WithMany()
                        .HasForeignKey("BenhNhanId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Patient");
                });

            modelBuilder.Entity("QuanLyBenhVien.Models.Prescription", b =>
                {
                    b.HasOne("QuanLyBenhVien.Models.Doctor", "BacSiKe")
                        .WithMany()
                        .HasForeignKey("BacSiKeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("QuanLyBenhVien.Models.ExaminationRecord", "ExaminationRecord")
                        .WithOne()
                        .HasForeignKey("QuanLyBenhVien.Models.Prescription", "PhieuKhamId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("BacSiKe");

                    b.Navigation("ExaminationRecord");
                });

            modelBuilder.Entity("QuanLyBenhVien.Models.PrescriptionBatchAllocation", b =>
                {
                    b.HasOne("QuanLyBenhVien.Models.PrescriptionDetail", "ChiTietDonThuoc")
                        .WithMany()
                        .HasForeignKey("ChiTietDonThuocId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("QuanLyBenhVien.Models.MedicineBatch", "LoThuoc")
                        .WithMany()
                        .HasForeignKey("LoThuocId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ChiTietDonThuoc");

                    b.Navigation("LoThuoc");
                });

            modelBuilder.Entity("QuanLyBenhVien.Models.PrescriptionDetail", b =>
                {
                    b.HasOne("QuanLyBenhVien.Models.Prescription", "Prescription")
                        .WithMany("PrescriptionDetails")
                        .HasForeignKey("DonThuocId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("QuanLyBenhVien.Models.Medicine", "Medicine")
                        .WithMany()
                        .HasForeignKey("ThuocId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Medicine");

                    b.Navigation("Prescription");
                });

            modelBuilder.Entity("QuanLyBenhVien.Models.Review", b =>
                {
                    b.HasOne("QuanLyBenhVien.Models.Doctor", "Doctor")
                        .WithMany()
                        .HasForeignKey("BacSiId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("QuanLyBenhVien.Models.Patient", "Patient")
                        .WithMany()
                        .HasForeignKey("BenhNhanId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("QuanLyBenhVien.Models.Appointment", "Appointment")
                        .WithMany()
                        .HasForeignKey("LichKhamId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Appointment");

                    b.Navigation("Doctor");

                    b.Navigation("Patient");
                });

            modelBuilder.Entity("QuanLyBenhVien.Models.RolePermission", b =>
                {
                    b.HasOne("QuanLyBenhVien.Models.User", "CapNhatBoi")
                        .WithMany()
                        .HasForeignKey("CapNhatBoiId");

                    b.Navigation("CapNhatBoi");
                });

            modelBuilder.Entity("QuanLyBenhVien.Models.Service", b =>
                {
                    b.HasOne("QuanLyBenhVien.Models.Department", "Department")
                        .WithMany()
                        .HasForeignKey("KhoaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Department");
                });

            modelBuilder.Entity("QuanLyBenhVien.Models.User", b =>
                {
                    b.HasOne("QuanLyBenhVien.Models.User", "XoaBoi")
                        .WithMany()
                        .HasForeignKey("XoaBoiId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.Navigation("XoaBoi");
                });

            modelBuilder.Entity("QuanLyBenhVien.Models.Doctor", b =>
                {
                    b.Navigation("WorkSchedules");
                });

            modelBuilder.Entity("QuanLyBenhVien.Models.DrugAllergyGroup", b =>
                {
                    b.Navigation("ThanhVien");
                });

            modelBuilder.Entity("QuanLyBenhVien.Models.GoodsReceipt", b =>
                {
                    b.Navigation("ChiTiet");
                });

            modelBuilder.Entity("QuanLyBenhVien.Models.Invoice", b =>
                {
                    b.Navigation("InvoiceDetails");
                });

            modelBuilder.Entity("QuanLyBenhVien.Models.LabOrder", b =>
                {
                    b.Navigation("ChiTiet");
                });

            modelBuilder.Entity("QuanLyBenhVien.Models.LabOrderBundle", b =>
                {
                    b.Navigation("ThanhVien");
                });

            modelBuilder.Entity("QuanLyBenhVien.Models.LabOrderItem", b =>
                {
                    b.Navigation("KetQua");
                });

            modelBuilder.Entity("QuanLyBenhVien.Models.LabResult", b =>
                {
                    b.Navigation("Files");
                });

            modelBuilder.Entity("QuanLyBenhVien.Models.LabServiceCatalog", b =>
                {
                    b.Navigation("ThuocCacBo");
                });

            modelBuilder.Entity("QuanLyBenhVien.Models.Medicine", b =>
                {
                    b.Navigation("LoThuocs");
                });

            modelBuilder.Entity("QuanLyBenhVien.Models.Patient", b =>
                {
                    b.Navigation("Dependents");
                });

            modelBuilder.Entity("QuanLyBenhVien.Models.Prescription", b =>
                {
                    b.Navigation("PrescriptionDetails");
                });

            modelBuilder.Entity("QuanLyBenhVien.Models.Supplier", b =>
                {
                    b.Navigation("PhieuNhaps");
                });

            modelBuilder.Entity("QuanLyBenhVien.Models.User", b =>
                {
                    b.Navigation("DoctorProfile");

                    b.Navigation("PatientProfile");
                });
#pragma warning restore 612, 618
        }
    }
}
