// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using QuanLyBenhVien.Data;

#nullable disable

namespace QuanLyBenhVien.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260622085110_AddDependentEntity")]
    partial class AddDependentEntity
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.9");

            modelBuilder.Entity("QuanLyBenhVien.Models.Appointment", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int?>("BacSiId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("BenhNhanId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("LyDoKham")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("NgayTao")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("ThoiGian")
                        .HasColumnType("TEXT");

                    b.Property<string>("TrangThai")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("BacSiId");

                    b.HasIndex("BenhNhanId");

                    b.ToTable("LichKham");
                });

            modelBuilder.Entity("QuanLyBenhVien.Models.AuditLog", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("ChiTiet")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("TEXT");

                    b.Property<string>("HanhDong")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("IpAddress")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<int?>("NguoiDungId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("ThoiGian")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("NguoiDungId");

                    b.ToTable("NhatKyHeThong");
                });

            modelBuilder.Entity("QuanLyBenhVien.Models.Department", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("MoTa")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<string>("TenKhoa")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("ViTri")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Khoa");
                });

            modelBuilder.Entity("QuanLyBenhVien.Models.Dependent", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("BenhNhanId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("GioiTinh")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("TEXT");

                    b.Property<string>("HoTen")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<int>("NamSinh")
                        .HasColumnType("INTEGER");

                    b.Property<string>("NhomMau")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("TEXT");

                    b.Property<string>("QuanHe")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<string>("SoBHYT")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<string>("TienSuBenhLy")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("BenhNhanId");

                    b.ToTable("NguoiThan");
                });

            modelBuilder.Entity("QuanLyBenhVien.Models.Doctor", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("ChuyenKhoa")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("HocVi")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<int>("KhoaId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("LichLamViec")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<int>("NguoiDungId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("SoNamKinhNghiem")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("KhoaId");

                    b.HasIndex("NguoiDungId")
                        .IsUnique();

                    b.ToTable("BacSi");
                });

            modelBuilder.Entity("QuanLyBenhVien.Models.ExaminationRecord", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<decimal?>("BMI")
                        .HasColumnType("decimal(4, 2)");

                    b.Property<decimal?>("CanNang")
                        .HasColumnType("decimal(5, 2)");

                    b.Property<string>("ChanDoan")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<string>("ChiDinhCLS")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<decimal?>("ChieuCao")
                        .HasColumnType("decimal(5, 2)");

                    b.Property<string>("HuyetAp")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.Property<string>("KetQuaCLS")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("TEXT");

                    b.Property<int>("LichKhamId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("LoiDan")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("NgayKham")
                        .HasColumnType("TEXT");

                    b.Property<decimal?>("NhietDo")
                        .HasColumnType("decimal(4, 1)");

                    b.Property<int?>("NhipTim")
                        .HasColumnType("INTEGER");

                    b.Property<string>("TrieuChung")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("LichKhamId");

                    b.ToTable("PhieuKham");
                });

            modelBuilder.Entity("QuanLyBenhVien.Models.Invoice", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("NgayTao")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("NgayThanhToan")
                        .HasColumnType("TEXT");

                    b.Property<int>("PhieuKhamId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("PhuongThuc")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<decimal>("TongTien")
                        .HasColumnType("decimal(18, 2)");

                    b.Property<string>("TrangThaiThanhToan")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("PhieuKhamId");

                    b.ToTable("HoaDon");
                });

            modelBuilder.Entity("QuanLyBenhVien.Models.InvoiceDetail", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("HoaDonId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("LoaiPhi")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<decimal>("SoTien")
                        .HasColumnType("decimal(18, 2)");

                    b.HasKey("Id");

                    b.HasIndex("HoaDonId");

                    b.ToTable("ChiTietHoaDon");
                });

            modelBuilder.Entity("QuanLyBenhVien.Models.Medicine", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("DonViTinh")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<decimal>("Gia")
                        .HasColumnType("decimal(18, 2)");

                    b.Property<string>("HoatChat")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("TEXT");

                    b.Property<int>("NguongToiThieu")
                        .HasColumnType("INTEGER");

                    b.Property<string>("TenThuoc")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("TEXT");

                    b.Property<int>("TonKho")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("Thuoc");
                });

            modelBuilder.Entity("QuanLyBenhVien.Models.MedicineBatch", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("HanSuDung")
                        .HasColumnType("TEXT");

                    b.Property<string>("SoLo")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<int>("SoLuongNhap")
                        .HasColumnType("INTEGER");

                    b.Property<int>("SoLuongTon")
                        .HasColumnType("INTEGER");

                    b.Property<int>("ThuocId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("ThuocId");

                    b.ToTable("LoThuoc");
                });

            modelBuilder.Entity("QuanLyBenhVien.Models.Notification", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<bool>("DaDoc")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("NgayGui")
                        .HasColumnType("TEXT");

                    b.Property<int>("NguoiDungId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("NoiDung")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("NguoiDungId");

                    b.ToTable("ThongBao");
                });

            modelBuilder.Entity("QuanLyBenhVien.Models.Patient", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("DiUng")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<string>("GioiTinh")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("NgaySinh")
                        .HasColumnType("TEXT");

                    b.Property<int>("NguoiDungId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("NhomMau")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("TEXT");

                    b.Property<string>("SoBHYT")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<string>("TienSuBenh")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("NguoiDungId")
                        .IsUnique();

                    b.ToTable("BenhNhan");
                });

            modelBuilder.Entity("QuanLyBenhVien.Models.Prescription", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("NgayKe")
                        .HasColumnType("TEXT");

                    b.Property<int>("PhieuKhamId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("PhieuKhamId");

                    b.ToTable("DonThuoc");
                });

            modelBuilder.Entity("QuanLyBenhVien.Models.PrescriptionDetail", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("DonThuocId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("LieuDung")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<int>("SoLuong")
                        .HasColumnType("INTEGER");

                    b.Property<int>("ThuocId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("DonThuocId");

                    b.HasIndex("ThuocId");

                    b.ToTable("ChiTietDonThuoc");
                });

            modelBuilder.Entity("QuanLyBenhVien.Models.Review", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("BacSiId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("BenhNhanId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("NgayTao")
                        .HasColumnType("TEXT");

                    b.Property<string>("NhanXet")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<int>("SoSao")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("BacSiId");

                    b.HasIndex("BenhNhanId");

                    b.ToTable("DanhGia");
                });

            modelBuilder.Entity("QuanLyBenhVien.Models.Service", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("Gia")
                        .HasColumnType("decimal(18, 2)");

                    b.Property<int>("KhoaId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("TenDichVu")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("KhoaId");

                    b.ToTable("DichVu");
                });

            modelBuilder.Entity("QuanLyBenhVien.Models.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("HoTen")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("MatKhauHash")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("NgayTao")
                        .HasColumnType("TEXT");

                    b.Property<string>("Sdt")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.Property<string>("TrangThai")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<string>("VaiTro")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("NguoiDung");
                });

            modelBuilder.Entity("QuanLyBenhVien.Models.Appointment", b =>
                {
                    b.HasOne("QuanLyBenhVien.Models.Doctor", "Doctor")
                        .WithMany()
                        .HasForeignKey("BacSiId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("QuanLyBenhVien.Models.Patient", "Patient")
                        .WithMany()
                        .HasForeignKey("BenhNhanId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Doctor");

                    b.Navigation("Patient");
                });

            modelBuilder.Entity("QuanLyBenhVien.Models.AuditLog", b =>
                {
                    b.HasOne("QuanLyBenhVien.Models.User", "User")
                        .WithMany()
                        .HasForeignKey("NguoiDungId");

                    b.Navigation("User");
                });

            modelBuilder.Entity("QuanLyBenhVien.Models.Dependent", b =>
                {
                    b.HasOne("QuanLyBenhVien.Models.Patient", "Patient")
                        .WithMany("Dependents")
                        .HasForeignKey("BenhNhanId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Patient");
                });

            modelBuilder.Entity("QuanLyBenhVien.Models.Doctor", b =>
                {
                    b.HasOne("QuanLyBenhVien.Models.Department", "Department")
                        .WithMany()
                        .HasForeignKey("KhoaId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("QuanLyBenhVien.Models.User", "User")
                        .WithOne("DoctorProfile")
                        .HasForeignKey("QuanLyBenhVien.Models.Doctor", "NguoiDungId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Department");

                    b.Navigation("User");
                });

            modelBuilder.Entity("QuanLyBenhVien.Models.ExaminationRecord", b =>
                {
                    b.HasOne("QuanLyBenhVien.Models.Appointment", "Appointment")
                        .WithMany()
                        .HasForeignKey("LichKhamId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Appointment");
                });

            modelBuilder.Entity("QuanLyBenhVien.Models.Invoice", b =>
                {
                    b.HasOne("QuanLyBenhVien.Models.ExaminationRecord", "ExaminationRecord")
                        .WithMany()
                        .HasForeignKey("PhieuKhamId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ExaminationRecord");
                });

            modelBuilder.Entity("QuanLyBenhVien.Models.InvoiceDetail", b =>
                {
                    b.HasOne("QuanLyBenhVien.Models.Invoice", "Invoice")
                        .WithMany("InvoiceDetails")
                        .HasForeignKey("HoaDonId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Invoice");
                });

            modelBuilder.Entity("QuanLyBenhVien.Models.MedicineBatch", b =>
                {
                    b.HasOne("QuanLyBenhVien.Models.Medicine", "Medicine")
                        .WithMany("LoThuocs")
                        .HasForeignKey("ThuocId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Medicine");
                });

            modelBuilder.Entity("QuanLyBenhVien.Models.Notification", b =>
                {
                    b.HasOne("QuanLyBenhVien.Models.User", "User")
                        .WithMany()
                        .HasForeignKey("NguoiDungId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("QuanLyBenhVien.Models.Patient", b =>
                {
                    b.HasOne("QuanLyBenhVien.Models.User", "User")
                        .WithOne("PatientProfile")
                        .HasForeignKey("QuanLyBenhVien.Models.Patient", "NguoiDungId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("QuanLyBenhVien.Models.Prescription", b =>
                {
                    b.HasOne("QuanLyBenhVien.Models.ExaminationRecord", "ExaminationRecord")
                        .WithMany()
                        .HasForeignKey("PhieuKhamId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ExaminationRecord");
                });

            modelBuilder.Entity("QuanLyBenhVien.Models.PrescriptionDetail", b =>
                {
                    b.HasOne("QuanLyBenhVien.Models.Prescription", "Prescription")
                        .WithMany("PrescriptionDetails")
                        .HasForeignKey("DonThuocId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("QuanLyBenhVien.Models.Medicine", "Medicine")
                        .WithMany()
                        .HasForeignKey("ThuocId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Medicine");

                    b.Navigation("Prescription");
                });

            modelBuilder.Entity("QuanLyBenhVien.Models.Review", b =>
                {
                    b.HasOne("QuanLyBenhVien.Models.Doctor", "Doctor")
                        .WithMany()
                        .HasForeignKey("BacSiId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("QuanLyBenhVien.Models.Patient", "Patient")
                        .WithMany()
                        .HasForeignKey("BenhNhanId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Doctor");

                    b.Navigation("Patient");
                });

            modelBuilder.Entity("QuanLyBenhVien.Models.Service", b =>
                {
                    b.HasOne("QuanLyBenhVien.Models.Department", "Department")
                        .WithMany()
                        .HasForeignKey("KhoaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Department");
                });

            modelBuilder.Entity("QuanLyBenhVien.Models.Invoice", b =>
                {
                    b.Navigation("InvoiceDetails");
                });

            modelBuilder.Entity("QuanLyBenhVien.Models.Medicine", b =>
                {
                    b.Navigation("LoThuocs");
                });

            modelBuilder.Entity("QuanLyBenhVien.Models.Patient", b =>
                {
                    b.Navigation("Dependents");
                });

            modelBuilder.Entity("QuanLyBenhVien.Models.Prescription", b =>
                {
                    b.Navigation("PrescriptionDetails");
                });

            modelBuilder.Entity("QuanLyBenhVien.Models.User", b =>
                {
                    b.Navigation("DoctorProfile");

                    b.Navigation("PatientProfile");
                });
#pragma warning restore 612, 618
        }
    }
}
