// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using QuanLyBenhVien.Data;

#nullable disable

namespace QuanLyBenhVien.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260730044849_DataIntegrityConstraints")]
    partial class DataIntegrityConstraints
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.9");

            modelBuilder.Entity("QuanLyBenhVien.Models.Appointment", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int?>("BacSiId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("BenhNhanId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("LyDoKham")
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("NgayTao")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<DateTime>("ThoiGian")
                        .HasColumnType("TEXT");

                    b.Property<string>("TrangThai")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("BacSiId");

                    b.HasIndex("BenhNhanId");

                    b.HasIndex("ThoiGian");

                    b.HasIndex("TrangThai");

                    b.ToTable("LichKham", t =>
                        {
                            t.HasCheckConstraint("CK_LichKham_TrangThai", "TrangThai IN ('ChoXacNhan','DaXacNhan','DangKham','HoanThanh','DaHuy','VangMat')");
                        });
                });

            modelBuilder.Entity("QuanLyBenhVien.Models.Article", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("AnhBia")
                        .HasMaxLength(300)
                        .HasColumnType("TEXT");

                    b.Property<string>("ChuyenMuc")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<bool>("DaXuatBan")
                        .HasColumnType("INTEGER");

                    b.Property<int>("LuotXem")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("NgayCapNhat")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("NgayDang")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<bool>("NoiBat")
                        .HasColumnType("INTEGER");

                    b.Property<string>("NoiDung")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("TacGia")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("TieuDe")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<string>("TomTat")
                        .IsRequired()
                        .HasMaxLength(400)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("TinTuc");
                });

            modelBuilder.Entity("QuanLyBenhVien.Models.AuditLog", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("ChiTiet")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("TEXT");

                    b.Property<int?>("DoiTuongId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("DoiTuongLoai")
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<string>("HanhDong")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("IpAddress")
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<int?>("NguoiDungId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("ThoiGian")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.HasKey("Id");

                    b.HasIndex("NguoiDungId");

                    b.ToTable("NhatKyHeThong");
                });

            modelBuilder.Entity("QuanLyBenhVien.Models.Department", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("MoTa")
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<string>("TenKhoa")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("ViTri")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Khoa");
                });

            modelBuilder.Entity("QuanLyBenhVien.Models.Dependent", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("BenhNhanId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("GioiTinh")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("TEXT");

                    b.Property<string>("HoTen")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<int>("NamSinh")
                        .HasColumnType("INTEGER");

                    b.Property<string>("NhomMau")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("TEXT");

                    b.Property<string>("QuanHe")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<string>("SoBHYT")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<string>("TienSuBenhLy")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("BenhNhanId");

                    b.ToTable("NguoiThan");
                });

            modelBuilder.Entity("QuanLyBenhVien.Models.Doctor", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("ChucVu")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<string>("ChuyenKhoa")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<bool>("DaXoa")
                        .HasColumnType("INTEGER");

                    b.Property<string>("HocVi")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<int>("KhoaId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("LichLamViec")
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("NgayXoa")
                        .HasColumnType("TEXT");

                    b.Property<int>("NguoiDungId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("SoNamKinhNghiem")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("XoaBoiId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("KhoaId");

                    b.HasIndex("NguoiDungId")
                        .IsUnique();

                    b.HasIndex("XoaBoiId");

                    b.ToTable("BacSi", t =>
                        {
                            t.HasCheckConstraint("CK_BacSi_ChucVu", "ChucVu IN ('Bác sĩ','Phó trưởng khoa','Trưởng khoa')");
                        });
                });

            modelBuilder.Entity("QuanLyBenhVien.Models.DoctorWorkSchedule", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("BacSiId")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("DangHoatDong")
                        .HasColumnType("INTEGER");

                    b.Property<TimeSpan>("GioBatDau")
                        .HasColumnType("TEXT");

                    b.Property<TimeSpan>("GioKetThuc")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("HieuLucDen")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("HieuLucTu")
                        .HasColumnType("TEXT");

                    b.Property<string>("PhongKham")
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<int>("SoBenhNhanToiDa")
                        .HasColumnType("INTEGER");

                    b.Property<int>("ThoiLuongKhamPhut")
                        .HasColumnType("INTEGER");

                    b.Property<int>("ThuTrongTuan")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("BacSiId", "ThuTrongTuan", "GioBatDau", "GioKetThuc")
                        .IsUnique();

                    b.ToTable("LichLamViecBacSi", t =>
                        {
                            t.HasCheckConstraint("CK_LichLamViecBacSi_GioKetThuc", "GioKetThuc > GioBatDau");

                            t.HasCheckConstraint("CK_LichLamViecBacSi_SoBenhNhanToiDa", "SoBenhNhanToiDa > 0");

                            t.HasCheckConstraint("CK_LichLamViecBacSi_ThoiLuongKhamPhut", "ThoiLuongKhamPhut BETWEEN 5 AND 240");
                        });
                });

            modelBuilder.Entity("QuanLyBenhVien.Models.ExaminationRecord", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<decimal?>("BMI")
                        .HasColumnType("decimal(4, 2)");

                    b.Property<decimal?>("CanNang")
                        .HasColumnType("decimal(5, 2)");

                    b.Property<string>("ChanDoan")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<string>("ChiDinhCLS")
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<decimal?>("ChieuCao")
                        .HasColumnType("decimal(5, 2)");

                    b.Property<string>("HuyetAp")
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.Property<string>("KetQuaCLS")
                        .HasMaxLength(1000)
                        .HasColumnType("TEXT");

                    b.Property<int>("LichKhamId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("LoiDan")
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("NgayKham")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<decimal?>("NhietDo")
                        .HasColumnType("decimal(4, 1)");

                    b.Property<int?>("NhipTim")
                        .HasColumnType("INTEGER");

                    b.Property<string>("TrieuChung")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("LichKhamId")
                        .IsUnique();

                    b.ToTable("PhieuKham");
                });

            modelBuilder.Entity("QuanLyBenhVien.Models.FamilyHistory", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("BenhNhanId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("GhiChu")
                        .HasMaxLength(300)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("NgayGhiNhan")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<string>("QuanHe")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<string>("TenBenh")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("BenhNhanId");

                    b.ToTable("TienSuGiaDinh");
                });

            modelBuilder.Entity("QuanLyBenhVien.Models.Immunization", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("BenhNhanId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("GhiChu")
                        .HasMaxLength(300)
                        .HasColumnType("TEXT");

                    b.Property<string>("MuiSo")
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("NgayTiem")
                        .HasColumnType("TEXT");

                    b.Property<string>("TenVaccine")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("BenhNhanId");

                    b.ToTable("TiemChung");
                });

            modelBuilder.Entity("QuanLyBenhVien.Models.Invoice", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("MaGiaoDich")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("NgayTao")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<DateTime?>("NgayThanhToan")
                        .HasColumnType("TEXT");

                    b.Property<int>("PhieuKhamId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("PhuongThuc")
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<decimal>("TongTien")
                        .HasColumnType("decimal(18, 2)");

                    b.Property<string>("TrangThaiThanhToan")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("PhieuKhamId")
                        .IsUnique();

                    b.ToTable("HoaDon", t =>
                        {
                            t.HasCheckConstraint("CK_HoaDon_PhuongThuc", "PhuongThuc IS NULL OR PhuongThuc IN ('TienMat','ChuyenKhoan','Online (MoMo)','Online (VNPay)','Online (ZaloPay)','Online')");

                            t.HasCheckConstraint("CK_HoaDon_TongTien", "TongTien >= 0");

                            t.HasCheckConstraint("CK_HoaDon_TrangThaiThanhToan", "TrangThaiThanhToan IN ('ChuaThanhToan','DaThanhToan','DangXuLy','QuaHan','ThanhToanThatBai','DaHuy')");
                        });
                });

            modelBuilder.Entity("QuanLyBenhVien.Models.InvoiceDetail", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("HoaDonId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("LoaiPhi")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<decimal>("SoTien")
                        .HasColumnType("decimal(18, 2)");

                    b.HasKey("Id");

                    b.HasIndex("HoaDonId");

                    b.ToTable("ChiTietHoaDon", t =>
                        {
                            t.HasCheckConstraint("CK_ChiTietHoaDon_SoTien", "SoTien >= 0");
                        });
                });

            modelBuilder.Entity("QuanLyBenhVien.Models.Medicine", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("DonViTinh")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<decimal>("Gia")
                        .HasColumnType("decimal(18, 2)");

                    b.Property<string>("HoatChat")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("TEXT");

                    b.Property<int>("NguongToiThieu")
                        .HasColumnType("INTEGER");

                    b.Property<string>("TenThuoc")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("TEXT");

                    b.Property<int>("TonKho")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("Thuoc", t =>
                        {
                            t.HasCheckConstraint("CK_Thuoc_Gia", "Gia >= 0");

                            t.HasCheckConstraint("CK_Thuoc_NguongToiThieu", "NguongToiThieu >= 0");

                            t.HasCheckConstraint("CK_Thuoc_TonKho", "TonKho >= 0");
                        });
                });

            modelBuilder.Entity("QuanLyBenhVien.Models.MedicineBatch", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("HanSuDung")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("NgayNhap")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasDefaultValueSql("'2000-01-01 00:00:00'");

                    b.Property<string>("SoLo")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<int>("SoLuongNhap")
                        .HasColumnType("INTEGER");

                    b.Property<int>("SoLuongTon")
                        .HasColumnType("INTEGER");

                    b.Property<int>("ThuocId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("ThuocId");

                    b.ToTable("LoThuoc", t =>
                        {
                            t.HasCheckConstraint("CK_LoThuoc_HanSuDung", "HanSuDung >= NgayNhap");

                            t.HasCheckConstraint("CK_LoThuoc_SoLuongNhap", "SoLuongNhap > 0");

                            t.HasCheckConstraint("CK_LoThuoc_SoLuongTon", "SoLuongTon >= 0");

                            t.HasCheckConstraint("CK_LoThuoc_TonKhongVuotQuaNhap", "SoLuongTon <= SoLuongNhap");
                        });
                });

            modelBuilder.Entity("QuanLyBenhVien.Models.Notification", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<bool>("DaDoc")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("NgayGui")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<int>("NguoiDungId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("NoiDung")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("NguoiDungId");

                    b.ToTable("ThongBao");
                });

            modelBuilder.Entity("QuanLyBenhVien.Models.Patient", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<bool>("DaXoa")
                        .HasColumnType("INTEGER");

                    b.Property<string>("DiUng")
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<string>("GioiTinh")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("NgayHetHanBHYT")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("NgaySinh")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("NgayXoa")
                        .HasColumnType("TEXT");

                    b.Property<int>("NguoiDungId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("NhomMau")
                        .HasMaxLength(10)
                        .HasColumnType("TEXT");

                    b.Property<string>("SoBHYT")
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<string>("SoCCCD")
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.Property<string>("TienSuBenh")
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<int?>("XoaBoiId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("NguoiDungId")
                        .IsUnique();

                    b.HasIndex("SoBHYT")
                        .IsUnique();

                    b.HasIndex("SoCCCD")
                        .IsUnique();

                    b.HasIndex("XoaBoiId");

                    b.ToTable("BenhNhan", t =>
                        {
                            t.HasCheckConstraint("CK_BenhNhan_NgaySinh", "NgaySinh <= CURRENT_TIMESTAMP");
                        });
                });

            modelBuilder.Entity("QuanLyBenhVien.Models.PatientDocument", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("BenhNhanId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ContentType")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("GhiChu")
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<long>("KichThuoc")
                        .HasColumnType("INTEGER");

                    b.Property<string>("LoaiTaiLieu")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("NgayTaiLen")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<string>("TenLuuTru")
                        .IsRequired()
                        .HasMaxLength(260)
                        .HasColumnType("TEXT");

                    b.Property<string>("TenTaiLieu")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("BenhNhanId");

                    b.ToTable("TaiLieuBenhNhan");
                });

            modelBuilder.Entity("QuanLyBenhVien.Models.PatientHealthMetric", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("BenhNhanId")
                        .HasColumnType("INTEGER");

                    b.Property<decimal?>("CanNang")
                        .HasColumnType("TEXT");

                    b.Property<decimal?>("ChieuCao")
                        .HasColumnType("TEXT");

                    b.Property<decimal?>("DuongHuyet")
                        .HasColumnType("TEXT");

                    b.Property<string>("GhiChu")
                        .HasMaxLength(300)
                        .HasColumnType("TEXT");

                    b.Property<int?>("HuyetApTamThu")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("HuyetApTamTruong")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("NgayDo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<DateTime>("NgayTao")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<int?>("NhipTim")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("BenhNhanId");

                    b.ToTable("ChiSoSucKhoeTuDo");
                });

            modelBuilder.Entity("QuanLyBenhVien.Models.Prescription", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("NgayKe")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<int>("PhieuKhamId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("PhieuKhamId")
                        .IsUnique();

                    b.ToTable("DonThuoc");
                });

            modelBuilder.Entity("QuanLyBenhVien.Models.PrescriptionDetail", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("DonThuocId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("LieuDung")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<int>("SoLuong")
                        .HasColumnType("INTEGER");

                    b.Property<int>("ThuocId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("DonThuocId");

                    b.HasIndex("ThuocId");

                    b.ToTable("ChiTietDonThuoc", t =>
                        {
                            t.HasCheckConstraint("CK_ChiTietDonThuoc_SoLuong", "SoLuong > 0");
                        });
                });

            modelBuilder.Entity("QuanLyBenhVien.Models.Review", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("BacSiId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("BenhNhanId")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("LichKhamId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("NgayTao")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<string>("NhanXet")
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<int>("SoSao")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("BacSiId");

                    b.HasIndex("BenhNhanId");

                    b.HasIndex("LichKhamId")
                        .IsUnique();

                    b.ToTable("DanhGia", t =>
                        {
                            t.HasCheckConstraint("CK_DanhGia_SoSao", "SoSao BETWEEN 1 AND 5");
                        });
                });

            modelBuilder.Entity("QuanLyBenhVien.Models.RolePermission", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int?>("CapNhatBoiId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CapNhatLuc")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<bool>("DuocPhep")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ModuleKey")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("VaiTro")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("CapNhatBoiId");

                    b.HasIndex("VaiTro", "ModuleKey")
                        .IsUnique();

                    b.ToTable("PhanQuyenVaiTro");
                });

            modelBuilder.Entity("QuanLyBenhVien.Models.Service", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("Gia")
                        .HasColumnType("decimal(18, 2)");

                    b.Property<int>("KhoaId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("TenDichVu")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("KhoaId");

                    b.ToTable("DichVu", t =>
                        {
                            t.HasCheckConstraint("CK_DichVu_Gia", "Gia >= 0");
                        });
                });

            modelBuilder.Entity("QuanLyBenhVien.Models.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("AnhDaiDien")
                        .HasMaxLength(260)
                        .HasColumnType("TEXT");

                    b.Property<bool>("DaXoa")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("HoTen")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("MatKhauHash")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("NgayTao")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<DateTime?>("NgayXoa")
                        .HasColumnType("TEXT");

                    b.Property<string>("Sdt")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.Property<string>("TrangThai")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<string>("VaiTro")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<int?>("XoaBoiId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.HasIndex("Sdt")
                        .IsUnique();

                    b.HasIndex("XoaBoiId");

                    b.ToTable("NguoiDung", t =>
                        {
                            t.HasCheckConstraint("CK_NguoiDung_TrangThai", "TrangThai IN ('Active','Blocked')");

                            t.HasCheckConstraint("CK_NguoiDung_VaiTro", "VaiTro IN ('Admin','Doctor','Patient')");
                        });
                });

            modelBuilder.Entity("QuanLyBenhVien.Models.Appointment", b =>
                {
                    b.HasOne("QuanLyBenhVien.Models.Doctor", "Doctor")
                        .WithMany()
                        .HasForeignKey("BacSiId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("QuanLyBenhVien.Models.Patient", "Patient")
                        .WithMany()
                        .HasForeignKey("BenhNhanId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Doctor");

                    b.Navigation("Patient");
                });

            modelBuilder.Entity("QuanLyBenhVien.Models.AuditLog", b =>
                {
                    b.HasOne("QuanLyBenhVien.Models.User", "User")
                        .WithMany()
                        .HasForeignKey("NguoiDungId");

                    b.Navigation("User");
                });

            modelBuilder.Entity("QuanLyBenhVien.Models.Dependent", b =>
                {
                    b.HasOne("QuanLyBenhVien.Models.Patient", "Patient")
                        .WithMany("Dependents")
                        .HasForeignKey("BenhNhanId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Patient");
                });

            modelBuilder.Entity("QuanLyBenhVien.Models.Doctor", b =>
                {
                    b.HasOne("QuanLyBenhVien.Models.Department", "Department")
                        .WithMany()
                        .HasForeignKey("KhoaId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("QuanLyBenhVien.Models.User", "User")
                        .WithOne("DoctorProfile")
                        .HasForeignKey("QuanLyBenhVien.Models.Doctor", "NguoiDungId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("QuanLyBenhVien.Models.User", "XoaBoi")
                        .WithMany()
                        .HasForeignKey("XoaBoiId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Department");

                    b.Navigation("User");

                    b.Navigation("XoaBoi");
                });

            modelBuilder.Entity("QuanLyBenhVien.Models.DoctorWorkSchedule", b =>
                {
                    b.HasOne("QuanLyBenhVien.Models.Doctor", "Doctor")
                        .WithMany("WorkSchedules")
                        .HasForeignKey("BacSiId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Doctor");
                });

            modelBuilder.Entity("QuanLyBenhVien.Models.ExaminationRecord", b =>
                {
                    b.HasOne("QuanLyBenhVien.Models.Appointment", "Appointment")
                        .WithOne()
                        .HasForeignKey("QuanLyBenhVien.Models.ExaminationRecord", "LichKhamId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Appointment");
                });

            modelBuilder.Entity("QuanLyBenhVien.Models.FamilyHistory", b =>
                {
                    b.HasOne("QuanLyBenhVien.Models.Patient", "Patient")
                        .WithMany()
                        .HasForeignKey("BenhNhanId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Patient");
                });

            modelBuilder.Entity("QuanLyBenhVien.Models.Immunization", b =>
                {
                    b.HasOne("QuanLyBenhVien.Models.Patient", "Patient")
                        .WithMany()
                        .HasForeignKey("BenhNhanId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Patient");
                });

            modelBuilder.Entity("QuanLyBenhVien.Models.Invoice", b =>
                {
                    b.HasOne("QuanLyBenhVien.Models.ExaminationRecord", "ExaminationRecord")
                        .WithOne()
                        .HasForeignKey("QuanLyBenhVien.Models.Invoice", "PhieuKhamId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("ExaminationRecord");
                });

            modelBuilder.Entity("QuanLyBenhVien.Models.InvoiceDetail", b =>
                {
                    b.HasOne("QuanLyBenhVien.Models.Invoice", "Invoice")
                        .WithMany("InvoiceDetails")
                        .HasForeignKey("HoaDonId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Invoice");
                });

            modelBuilder.Entity("QuanLyBenhVien.Models.MedicineBatch", b =>
                {
                    b.HasOne("QuanLyBenhVien.Models.Medicine", "Medicine")
                        .WithMany("LoThuocs")
                        .HasForeignKey("ThuocId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Medicine");
                });

            modelBuilder.Entity("QuanLyBenhVien.Models.Notification", b =>
                {
                    b.HasOne("QuanLyBenhVien.Models.User", "User")
                        .WithMany()
                        .HasForeignKey("NguoiDungId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("QuanLyBenhVien.Models.Patient", b =>
                {
                    b.HasOne("QuanLyBenhVien.Models.User", "User")
                        .WithOne("PatientProfile")
                        .HasForeignKey("QuanLyBenhVien.Models.Patient", "NguoiDungId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("QuanLyBenhVien.Models.User", "XoaBoi")
                        .WithMany()
                        .HasForeignKey("XoaBoiId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("User");

                    b.Navigation("XoaBoi");
                });

            modelBuilder.Entity("QuanLyBenhVien.Models.PatientDocument", b =>
                {
                    b.HasOne("QuanLyBenhVien.Models.Patient", "Patient")
                        .WithMany()
                        .HasForeignKey("BenhNhanId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Patient");
                });

            modelBuilder.Entity("QuanLyBenhVien.Models.PatientHealthMetric", b =>
                {
                    b.HasOne("QuanLyBenhVien.Models.Patient", "Patient")
                        .WithMany()
                        .HasForeignKey("BenhNhanId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Patient");
                });

            modelBuilder.Entity("QuanLyBenhVien.Models.Prescription", b =>
                {
                    b.HasOne("QuanLyBenhVien.Models.ExaminationRecord", "ExaminationRecord")
                        .WithOne()
                        .HasForeignKey("QuanLyBenhVien.Models.Prescription", "PhieuKhamId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("ExaminationRecord");
                });

            modelBuilder.Entity("QuanLyBenhVien.Models.PrescriptionDetail", b =>
                {
                    b.HasOne("QuanLyBenhVien.Models.Prescription", "Prescription")
                        .WithMany("PrescriptionDetails")
                        .HasForeignKey("DonThuocId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("QuanLyBenhVien.Models.Medicine", "Medicine")
                        .WithMany()
                        .HasForeignKey("ThuocId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Medicine");

                    b.Navigation("Prescription");
                });

            modelBuilder.Entity("QuanLyBenhVien.Models.Review", b =>
                {
                    b.HasOne("QuanLyBenhVien.Models.Doctor", "Doctor")
                        .WithMany()
                        .HasForeignKey("BacSiId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("QuanLyBenhVien.Models.Patient", "Patient")
                        .WithMany()
                        .HasForeignKey("BenhNhanId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("QuanLyBenhVien.Models.Appointment", "Appointment")
                        .WithMany()
                        .HasForeignKey("LichKhamId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Appointment");

                    b.Navigation("Doctor");

                    b.Navigation("Patient");
                });

            modelBuilder.Entity("QuanLyBenhVien.Models.RolePermission", b =>
                {
                    b.HasOne("QuanLyBenhVien.Models.User", "CapNhatBoi")
                        .WithMany()
                        .HasForeignKey("CapNhatBoiId");

                    b.Navigation("CapNhatBoi");
                });

            modelBuilder.Entity("QuanLyBenhVien.Models.Service", b =>
                {
                    b.HasOne("QuanLyBenhVien.Models.Department", "Department")
                        .WithMany()
                        .HasForeignKey("KhoaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Department");
                });

            modelBuilder.Entity("QuanLyBenhVien.Models.User", b =>
                {
                    b.HasOne("QuanLyBenhVien.Models.User", "XoaBoi")
                        .WithMany()
                        .HasForeignKey("XoaBoiId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.Navigation("XoaBoi");
                });

            modelBuilder.Entity("QuanLyBenhVien.Models.Doctor", b =>
                {
                    b.Navigation("WorkSchedules");
                });

            modelBuilder.Entity("QuanLyBenhVien.Models.Invoice", b =>
                {
                    b.Navigation("InvoiceDetails");
                });

            modelBuilder.Entity("QuanLyBenhVien.Models.Medicine", b =>
                {
                    b.Navigation("LoThuocs");
                });

            modelBuilder.Entity("QuanLyBenhVien.Models.Patient", b =>
                {
                    b.Navigation("Dependents");
                });

            modelBuilder.Entity("QuanLyBenhVien.Models.Prescription", b =>
                {
                    b.Navigation("PrescriptionDetails");
                });

            modelBuilder.Entity("QuanLyBenhVien.Models.User", b =>
                {
                    b.Navigation("DoctorProfile");

                    b.Navigation("PatientProfile");
                });
#pragma warning restore 612, 618
        }
    }
}
